# Generated by Django 2.1.4 on 2019-03-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TASK', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
