# Generated by Django 2.1.4 on 2019-03-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TASK', '0003_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
